// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using frostpunk2_ciekawostki.Data;

#nullable disable

namespace frostpunk2_ciekawostki.Migrations
{
    [DbContext(typeof(FrostpunkContext))]
    [Migration("20260125202231_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("frostpunk2_ciekawostki.Models.Ciekawostka", b =>
                {
                    b.Property<int>("CiekawostkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ZdjeciaURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CiekawostkaId");

                    b.ToTable("Ciekawostki");
                });
#pragma warning restore 612, 618
        }
    }
}
